export const SAMPLE_SONGS = [
  {
    id: "wonderwall",
    title: "Wonderwall",
    artist: "Oasis",
    capo: 2,
    difficulty: 2,
    patternId: 4,
    bpm: 87,
    sections: [
      { type: "verse", label: "Verse 1", lines: [
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 24 }], lyric: "Today is gonna be the day that they're" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "gonna throw it back to you" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 24 }], lyric: "By now you should've somehow realised" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "what you gotta do" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 24 }], lyric: "I don't believe that anybody" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "feels the way I do about you now" },
      ]},
      { type: "verse", label: "Verse 2", lines: [
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 24 }], lyric: "Backbeat, the word is on the street that the" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "fire in your heart is out" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 24 }], lyric: "I'm sure you've heard it all before but you" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "never really had a doubt" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 24 }], lyric: "I don't believe that anybody" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "feels the way I do about you now" },
      ]},
      { type: "chorus", label: "Pre-Chorus", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 18 }], lyric: "And all the roads we have to walk are winding" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 18 }], lyric: "And all the lights that lead us there are blinding" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "There are many things that I would" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "G", pos: 18 }], lyric: "like to say to you but I don't know how" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 10 }, { chord: "G", pos: 18 }], lyric: "Because maybe..." },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "you're gonna be the one that saves me" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 10 }, { chord: "G", pos: 18 }], lyric: "And after all..." },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "you're my wonderwall" },
      ]},
      { type: "verse", label: "Verse 3", lines: [
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 24 }], lyric: "Today was gonna be the day but they'll" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "never throw it back to you" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 24 }], lyric: "By now you should've somehow realised" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "what you're not to do" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 24 }], lyric: "I don't believe that anybody" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "feels the way I do about you now" },
      ]},
      { type: "chorus", label: "Pre-Chorus 2", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 18 }], lyric: "And all the roads that lead you there were winding" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 18 }], lyric: "And all the lights that light the way are blinding" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "There are many things that I would" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "G", pos: 18 }], lyric: "like to say to you but I don't know how" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 10 }, { chord: "G", pos: 18 }], lyric: "I said maybe..." },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "you're gonna be the one that saves me" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 10 }, { chord: "G", pos: 18 }], lyric: "And after all..." },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "you're my wonderwall" },
      ]},
      { type: "outro", label: "Outro", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 10 }, { chord: "G", pos: 18 }], lyric: "I said maybe..." },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "you're gonna be the one that saves me" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 10 }, { chord: "G", pos: 18 }], lyric: "you're gonna be the one that saves me" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "you're gonna be the one that saves me" },
      ]},
    ]
  },
  {
    id: "hallelujah",
    title: "Hallelujah",
    artist: "Leonard Cohen",
    capo: 0,
    difficulty: 2,
    patternId: 5,
    bpm: 56,
    sections: [
      { type: "verse", label: "Verse 1", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "Am", pos: 24 }], lyric: "I've heard there was a secret chord" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Am", pos: 24 }], lyric: "That David played and it pleased the Lord" },
        { chords: [{ chord: "F", pos: 0 }, { chord: "G", pos: 18 }], lyric: "But you don't really care for music" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 18 }], lyric: "do ya?" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "F", pos: 10 }, { chord: "G", pos: 18 }], lyric: "It goes like this, the fourth, the fifth" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 18 }], lyric: "The minor fall, the major lift" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "E", pos: 10 }, { chord: "Am", pos: 18 }], lyric: "The baffled king composing" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "F", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 10 }, { chord: "C", pos: 20 }], lyric: "Hallelu-u-u-jah" },
      ]},
      { type: "verse", label: "Verse 2", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "Am", pos: 24 }], lyric: "Your faith was strong but you needed proof" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Am", pos: 24 }], lyric: "You saw her bathing on the roof" },
        { chords: [{ chord: "F", pos: 0 }, { chord: "G", pos: 18 }], lyric: "Her beauty and the moonlight" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 18 }], lyric: "overthrew ya" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "F", pos: 10 }, { chord: "G", pos: 18 }], lyric: "She tied you to a kitchen chair" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 18 }], lyric: "She broke your throne, she cut your hair" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "E", pos: 10 }, { chord: "Am", pos: 18 }], lyric: "And from your lips she drew the" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "F", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 10 }, { chord: "C", pos: 20 }], lyric: "Hallelu-u-u-jah" },
      ]},
      { type: "verse", label: "Verse 3", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "Am", pos: 24 }], lyric: "Baby I've been here before" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Am", pos: 24 }], lyric: "I know this room, I've walked this floor" },
        { chords: [{ chord: "F", pos: 0 }, { chord: "G", pos: 18 }], lyric: "I used to live alone" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 18 }], lyric: "before I knew ya" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "F", pos: 10 }, { chord: "G", pos: 18 }], lyric: "I've seen your flag on the marble arch" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 18 }], lyric: "Love is not a victory march" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "E", pos: 10 }, { chord: "Am", pos: 18 }], lyric: "It's a cold and it's a broken" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "F", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 10 }, { chord: "C", pos: 20 }], lyric: "Hallelu-u-u-jah" },
      ]},
      { type: "verse", label: "Verse 4", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "Am", pos: 24 }], lyric: "There was a time you let me know" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Am", pos: 24 }], lyric: "What's real and going on below" },
        { chords: [{ chord: "F", pos: 0 }, { chord: "G", pos: 18 }], lyric: "But now you never show" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 18 }], lyric: "it to me, do ya?" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "F", pos: 10 }, { chord: "G", pos: 18 }], lyric: "Remember when I moved in you" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 18 }], lyric: "The holy dove was moving too" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "E", pos: 10 }, { chord: "Am", pos: 18 }], lyric: "And every breath we drew was" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "F", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 10 }, { chord: "C", pos: 20 }], lyric: "Hallelu-u-u-jah" },
      ]},
      { type: "verse", label: "Verse 5", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "Am", pos: 24 }], lyric: "I did my best, it wasn't much" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Am", pos: 24 }], lyric: "I couldn't feel, so I tried to touch" },
        { chords: [{ chord: "F", pos: 0 }, { chord: "G", pos: 18 }], lyric: "I've told the truth, I didn't come" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 18 }], lyric: "to fool ya" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "F", pos: 10 }, { chord: "G", pos: 18 }], lyric: "And even though it all went wrong" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 18 }], lyric: "I'll stand before the Lord of Song" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "E", pos: 10 }, { chord: "Am", pos: 18 }], lyric: "With nothing on my tongue but" },
      ]},
      { type: "chorus", label: "Chorus (Final)", lines: [
        { chords: [{ chord: "F", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 10 }, { chord: "C", pos: 20 }], lyric: "Hallelu-u-u-jah" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 10 }, { chord: "C", pos: 20 }], lyric: "Hallelu-u-u-jah" },
      ]},
    ]
  },
  {
    id: "fastcar",
    title: "Fast Car",
    artist: "Tracy Chapman",
    capo: 2,
    difficulty: 2,
    patternId: 2,
    bpm: 105,
    sections: [
      { type: "info", label: "Info", lines: [
        { chords: [], lyric: "Capo 2. Four chords throughout: C G Em D. Verses are fingerpicked (work up to that), chorus is strummed. Great for building right-hand independence." },
      ]},
      { type: "verse", label: "Verse 1", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "You got a fast car, and" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "I want a ticket to anywhere" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "Maybe we make a deal" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Maybe together we can get somewhere" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "Any place is better" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Starting from zero got nothing to lose" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "Maybe we'll make something, but" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "me myself I got nothing to prove" },
      ]},
      { type: "verse", label: "Verse 2", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "You got a fast car, but" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "is it fast enough so we can fly away?" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "We gotta make a decision" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Leave tonight or live and die this way" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "C", pos: 0 }], lyric: "So I remember when we were driving," },
        { chords: [{ chord: "G", pos: 0 }], lyric: "driving in your car" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "The speed so fast I felt like I was drunk" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "City lights lay out before us" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 16 }, { chord: "D", pos: 24 }], lyric: "and I had a feeling that I belonged" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 16 }, { chord: "D", pos: 24 }], lyric: "and I had a feeling I could be someone" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 16 }], lyric: "be someone, be someone" },
      ]},
      { type: "verse", label: "Verse 3", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "You got a fast car, and" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "I got a plan to get us out of here" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "I been working at the convenience store" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Managed to save just a little bit of money" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "Won't have to drive too far" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Just 'cross the border and into the city" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "You and I can both get jobs and" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "finally see what it means to be living" },
      ]},
      { type: "verse", label: "Verse 4", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "You got a fast car, and" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "we go cruising to entertain ourselves" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "You still ain't got a job and" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "I work in a market as a checkout girl" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "I know things will get better" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "You'll find work and I'll get promoted" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "We'll move out of the shelter" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Buy a big house and live in the suburbs" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "C", pos: 0 }], lyric: "So I remember when we were driving," },
        { chords: [{ chord: "G", pos: 0 }], lyric: "driving in your car" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "The speed so fast I felt like I was drunk" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "City lights lay out before us" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 16 }, { chord: "D", pos: 24 }], lyric: "and I had a feeling that I belonged" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 16 }, { chord: "D", pos: 24 }], lyric: "and I had a feeling I could be someone" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 16 }], lyric: "be someone, be someone" },
      ]},
      { type: "verse", label: "Verse 5", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "You got a fast car, and" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "I got a job that pays all our bills" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "You stay out drinking late at the bar" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "See more of your friends than you do of your kids" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "I'd always hoped for better" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Thought maybe together you and me would find it" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "I got no plans, I ain't going nowhere" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "So take your fast car and keep on driving" },
      ]},
      { type: "chorus", label: "Chorus (Final)", lines: [
        { chords: [{ chord: "C", pos: 0 }], lyric: "So I remember when we were driving," },
        { chords: [{ chord: "G", pos: 0 }], lyric: "driving in your car" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "The speed so fast I felt like I was drunk" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "City lights lay out before us" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 16 }, { chord: "D", pos: 24 }], lyric: "and I had a feeling that I belonged" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 16 }, { chord: "D", pos: 24 }], lyric: "and I had a feeling I could be someone" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 16 }], lyric: "be someone, be someone" },
      ]},
      { type: "verse", label: "Outro", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "You got a fast car, but" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "is it fast enough so you can fly away?" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "You gotta make a decision" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Leave tonight or live and die this way" },
      ]},
    ]
  },
  {
    id: "someoneyouloved",
    title: "Someone You Loved",
    artist: "Lewis Capaldi",
    capo: 1,
    difficulty: 1,
    patternId: 2,
    bpm: 110,
    sections: [
      { type: "info", label: "Info", lines: [
        { chords: [], lyric: "Capo 1. Same four chords the whole song: C G Am F. One of the easiest songs to strum along to — focus on getting the rhythm solid." },
      ]},
      { type: "verse", label: "Verse 1", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 24 }], lyric: "I'm going under and this time" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 24 }], lyric: "I fear there's no one to save me" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 24 }], lyric: "This all or nothing really got a way" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 24 }], lyric: "of driving me crazy" },
      ]},
      { type: "verse", label: "Pre-Chorus", lines: [
        { chords: [{ chord: "C", pos: 0 }], lyric: "I need somebody to heal" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "Somebody to know" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "Somebody to have" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "Somebody to hold" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "It's easy to say" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "But it's never the same" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "I guess I kinda liked the way" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "you numbed all the pain" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "C", pos: 0 }], lyric: "Now the day bleeds" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "Into nightfall" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "And you're not here" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "To get me through it all" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "I let my guard down" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "And then you pulled the rug" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "I was getting kinda used to" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "being someone you loved" },
      ]},
      { type: "verse", label: "Verse 2", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 24 }], lyric: "I'm going under and this time" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 24 }], lyric: "I fear there's no one to turn to" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 24 }], lyric: "This all or nothing way of loving" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 24 }], lyric: "got me sleeping without you" },
      ]},
      { type: "verse", label: "Pre-Chorus", lines: [
        { chords: [{ chord: "C", pos: 0 }], lyric: "Now I need somebody to know" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "Somebody to heal" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "Somebody to have" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "Just to know how it feels" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "It's easy to say" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "But it's never the same" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "I guess I kinda liked the way" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "you numbed all the pain" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "C", pos: 0 }], lyric: "Now the day bleeds" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "Into nightfall" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "And you're not here" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "To get me through it all" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "I let my guard down" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "And then you pulled the rug" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "I was getting kinda used to" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "being someone you loved" },
      ]},
      { type: "bridge", label: "Bridge", lines: [
        { chords: [{ chord: "C", pos: 0 }], lyric: "I let my guard down" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "I let my guard down" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 20 }], lyric: "I was getting kinda used to being someone you loved" },
      ]},
      { type: "chorus", label: "Chorus (Final)", lines: [
        { chords: [{ chord: "C", pos: 0 }], lyric: "Now the day bleeds" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "Into nightfall" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "And you're not here" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "To get me through it all" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "I let my guard down" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "And then you pulled the rug" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "I was getting kinda used to" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "being someone you loved" },
      ]},
    ]
  },
  {
    id: "allofme",
    title: "All of Me",
    artist: "John Legend",
    capo: 0,
    difficulty: 2,
    patternId: 5,
    bpm: 63,
    sections: [
      { type: "info", label: "Info", lines: [
        { chords: [], lyric: "No capo needed. Em C G D throughout. Slow tempo — good for practising smooth chord changes. The Am in the bridge is a nice easy addition." },
      ]},
      { type: "verse", label: "Verse 1", lines: [
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 20 }], lyric: "What would I do without your smart mouth" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Drawing me in, and you kicking me out" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 20 }], lyric: "Got my head spinning, no kidding" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "I can't pin you down" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 20 }], lyric: "What's going on in that beautiful mind" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "I'm on your magical mystery ride" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 20 }], lyric: "And I'm so dizzy, don't know what hit me" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "But I'll be alright" },
      ]},
      { type: "verse", label: "Pre-Chorus", lines: [
        { chords: [{ chord: "Am", pos: 0 }], lyric: "My head's under water" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "But I'm breathing fine" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "You're crazy and I'm out of my mind" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "G", pos: 0 }], lyric: "'Cause all of me" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "loves all of you" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "Love your curves and all your edges" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "All your perfect imperfections" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "Give your all to me" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "I'll give my all to you" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "You're my end and my beginning" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "Even when I lose I'm winning" },
      ]},
      { type: "verse", label: "Verse 2", lines: [
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 20 }], lyric: "How many times do I have to tell you" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Even when you're crying you're beautiful too" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 20 }], lyric: "The world is beating you down" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "I'm around through every mood" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 20 }], lyric: "You're my downfall, you're my muse" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "My worst distraction, my rhythm and blues" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 20 }], lyric: "I can't stop singing, it's ringing" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "in my head for you" },
      ]},
      { type: "verse", label: "Pre-Chorus", lines: [
        { chords: [{ chord: "Am", pos: 0 }], lyric: "My head's under water" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "But I'm breathing fine" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "You're crazy and I'm out of my mind" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "G", pos: 0 }], lyric: "'Cause all of me" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "loves all of you" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "Love your curves and all your edges" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "All your perfect imperfections" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "Give your all to me" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "I'll give my all to you" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "You're my end and my beginning" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "Even when I lose I'm winning" },
      ]},
      { type: "bridge", label: "Bridge", lines: [
        { chords: [{ chord: "Am", pos: 0 }], lyric: "Give me all of you" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "Cards on the table, we're both showing hearts" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "Risking it all, though it's hard" },
      ]},
      { type: "chorus", label: "Chorus (Final)", lines: [
        { chords: [{ chord: "G", pos: 0 }], lyric: "'Cause all of me" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "loves all of you" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "Love your curves and all your edges" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "All your perfect imperfections" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "Give your all to me" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "I'll give my all to you" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "You're my end and my beginning" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "Even when I lose I'm winning" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "'Cause I give you all of me" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "And you give me all of you" },
      ]},
    ]
  },
  {
    id: "countryroads",
    title: "Take Me Home, Country Roads",
    artist: "John Denver",
    capo: 2,
    difficulty: 1,
    patternId: 4,
    bpm: 82,
    sections: [
      { type: "info", label: "Info", lines: [
        { chords: [], lyric: "Capo 2. Mostly open chords you already know. The F in the bridge is a barre — good practice! You can substitute Fmaj7 (xx3210) if F is still tricky." },
      ]},
      { type: "verse", label: "Verse 1", lines: [
        { chords: [{ chord: "G", pos: 0 }, { chord: "Em", pos: 24 }], lyric: "Almost heaven, West Virginia" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "C", pos: 14 }, { chord: "G", pos: 24 }], lyric: "Blue Ridge Mountains, Shenandoah River" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "Em", pos: 24 }], lyric: "Life is old there, older than the trees" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "C", pos: 14 }, { chord: "G", pos: 24 }], lyric: "Younger than the mountains, growing like a breeze" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Country roads, take me home" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 20 }], lyric: "To the place I belong" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "West Virginia, mountain mama" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "Take me home, country roads" },
      ]},
      { type: "verse", label: "Verse 2", lines: [
        { chords: [{ chord: "G", pos: 0 }, { chord: "Em", pos: 24 }], lyric: "All my memories gather round her" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "C", pos: 14 }, { chord: "G", pos: 24 }], lyric: "Miner's lady, stranger to blue water" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "Em", pos: 24 }], lyric: "Dark and dusty, painted on the sky" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "C", pos: 14 }, { chord: "G", pos: 24 }], lyric: "Misty taste of moonshine, teardrop in my eye" },
      ]},
      { type: "bridge", label: "Bridge", lines: [
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 16 }], lyric: "I hear her voice in the mornin' hour she calls me" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "C", pos: 12 }, { chord: "G", pos: 24 }], lyric: "The radio reminds me of my home far away" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "F", pos: 24 }], lyric: "And drivin' down the road I get a feelin' that I" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 14 }], lyric: "should have been home yesterday" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "yesterday" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Country roads, take me home" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 20 }], lyric: "To the place I belong" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "West Virginia, mountain mama" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "Take me home, country roads" },
      ]},
      { type: "outro", label: "Outro", lines: [
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Take me home, down country roads" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "Take me home, down country roads" },
      ]},
    ]
  },
  {
    id: "livinonaprayer",
    title: "Livin' On A Prayer",
    artist: "Bon Jovi",
    capo: 2,
    difficulty: 2,
    patternId: 4,
    bpm: 123,
    sections: [
      { type: "info", label: "Info", lines: [
        { chords: [], lyric: "Capo 2 puts original key Cm into Am shapes. Power-chord driven rock — strum hard on the downbeats. The Em-C-D-Em pattern drives the chorus." },
      ]},
      { type: "verse", label: "Verse 1", lines: [
        { chords: [{ chord: "Em", pos: 0 }], lyric: "Tommy used to work on the docks" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "Union's been on strike, he's down on his luck" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 16 }], lyric: "It's tough... so tough" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "Gina works the diner all day" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "Working for her man, she brings home her pay" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 16 }], lyric: "For love... for love" },
      ]},
      { type: "chorus", label: "Pre-Chorus", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 14 }], lyric: "She says we've got to hold on to what we've got" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 14 }], lyric: "It doesn't make a difference if we make it or not" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 14 }], lyric: "We've got each other and that's a lot" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 14 }], lyric: "For love, we'll give it a shot" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 12 }], lyric: "Whoa, we're half way there" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "Em", pos: 12 }], lyric: "Whoa-oh, livin' on a prayer" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 12 }], lyric: "Take my hand, we'll make it I swear" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "Em", pos: 12 }], lyric: "Whoa-oh, livin' on a prayer" },
      ]},
      { type: "verse", label: "Verse 2", lines: [
        { chords: [{ chord: "Em", pos: 0 }], lyric: "Tommy's got his six-string in hock" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "Now he's holding in what he used to make it talk" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 16 }], lyric: "So tough... it's tough" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "Gina dreams of running away" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "When she cries in the night Tommy whispers" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 16 }], lyric: "Baby it's okay... someday" },
      ]},
      { type: "chorus", label: "Pre-Chorus 2", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 14 }], lyric: "We've got to hold on to what we've got" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 14 }], lyric: "It doesn't make a difference if we make it or not" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 14 }], lyric: "We've got each other and that's a lot" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 14 }], lyric: "For love, we'll give it a shot" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 12 }], lyric: "Whoa, we're half way there" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "Em", pos: 12 }], lyric: "Whoa-oh, livin' on a prayer" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 12 }], lyric: "Take my hand, we'll make it I swear" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "Em", pos: 12 }], lyric: "Whoa-oh, livin' on a prayer" },
      ]},
      { type: "bridge", label: "Bridge", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 14 }], lyric: "We've got to hold on, ready or not" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 14 }], lyric: "You live for the fight when it's all that you've got" },
      ]},
      { type: "chorus", label: "Chorus (Final)", lines: [
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 12 }], lyric: "Whoa, we're half way there" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "Em", pos: 12 }], lyric: "Whoa-oh, livin' on a prayer" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 12 }], lyric: "Take my hand, we'll make it I swear" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "Em", pos: 12 }], lyric: "Whoa-oh, livin' on a prayer" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 12 }], lyric: "Whoa, we're half way there" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "Em", pos: 12 }], lyric: "Whoa-oh, livin' on a prayer" },
      ]},
    ]
  },
  {
    id: "mrbrightside",
    title: "Mr. Brightside",
    artist: "The Killers",
    capo: 1,
    difficulty: 2,
    patternId: 4,
    bpm: 148,
    sections: [
      { type: "info", label: "Info", lines: [
        { chords: [], lyric: "Capo 1 to match the original key. Four chords the whole song: C G Am F. Fast tempo — start slow and build up. The trick is keeping the rhythm tight." },
      ]},
      { type: "verse", label: "Verse 1", lines: [
        { chords: [{ chord: "C", pos: 0 }], lyric: "Coming out of my cage" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "And I've been doing just fine" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "Gotta gotta be down" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "Because I want it all" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "It started out with a kiss" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "How did it end up like this?" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "It was only a kiss" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "It was only a kiss" },
      ]},
      { type: "verse", label: "Verse 2", lines: [
        { chords: [{ chord: "C", pos: 0 }], lyric: "Now I'm falling asleep" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "And she's calling a cab" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "While he's having a smoke" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "And she's taking a drag" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "Now they're going to bed" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "And my stomach is sick" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "And it's all in my head" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "But she's touching his" },
      ]},
      { type: "chorus", label: "Pre-Chorus", lines: [
        { chords: [{ chord: "C", pos: 0 }], lyric: "chest now" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "He takes off her dress now" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "Let me go" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "C", pos: 0 }], lyric: "I just can't look, it's killing me" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "And taking control" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 16 }], lyric: "Jealousy, turning saints into the sea" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "Swimming through sick lullabies" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "Choking on your alibis" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 16 }], lyric: "But it's just the price I pay" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "Destiny is calling me" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "Open up my eager eyes" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 16 }], lyric: "'Cause I'm Mr. Brightside" },
      ]},
      { type: "verse", label: "Verse 3", lines: [
        { chords: [{ chord: "C", pos: 0 }], lyric: "Coming out of my cage" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "And I've been doing just fine" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "Gotta gotta be down" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "Because I want it all" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "It started out with a kiss" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "How did it end up like this?" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "It was only a kiss" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "It was only a kiss" },
      ]},
      { type: "verse", label: "Verse 4", lines: [
        { chords: [{ chord: "C", pos: 0 }], lyric: "Now I'm falling asleep" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "And she's calling a cab" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "While he's having a smoke" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "And she's taking a drag" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "Now they're going to bed" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "And my stomach is sick" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "And it's all in my head" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "But she's touching his" },
      ]},
      { type: "chorus", label: "Pre-Chorus 2", lines: [
        { chords: [{ chord: "C", pos: 0 }], lyric: "chest now" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "He takes off her dress now" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "Let me go" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "" },
      ]},
      { type: "chorus", label: "Chorus (Final)", lines: [
        { chords: [{ chord: "C", pos: 0 }], lyric: "I just can't look, it's killing me" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "And taking control" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 16 }], lyric: "Jealousy, turning saints into the sea" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "Swimming through sick lullabies" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "Choking on your alibis" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 16 }], lyric: "But it's just the price I pay" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "Destiny is calling me" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "Open up my eager eyes" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 16 }], lyric: "'Cause I'm Mr. Brightside" },
      ]},
      { type: "outro", label: "Outro", lines: [
        { chords: [{ chord: "C", pos: 0 }], lyric: "I never..." },
        { chords: [{ chord: "G", pos: 0 }], lyric: "I never..." },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "I never..." },
        { chords: [{ chord: "F", pos: 0 }], lyric: "I never..." },
      ]},
    ]
  },
  {
    id: "overtherainbow",
    title: "Over The Rainbow",
    artist: "Israel Kamakawiwo'ole",
    capo: 0,
    difficulty: 1,
    patternId: 3,
    bpm: 85,
    sections: [
      { type: "info", label: "Info", lines: [
        { chords: [], lyric: "No capo. Originally ukulele but works beautifully on guitar. Island strum pattern fits perfectly. C Em Am F — all open chords. Relaxed and dreamy." },
      ]},
      { type: "intro", label: "Intro", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 14 }], lyric: "Ooh..." },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 14 }], lyric: "Ooh..." },
      ]},
      { type: "verse", label: "Verse 1", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 14 }], lyric: "Somewhere over the rainbow" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 14 }], lyric: "Way up high" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "F", pos: 14 }], lyric: "And the dreams that you dream of" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "Am", pos: 10 }, { chord: "F", pos: 20 }], lyric: "Once in a lullaby" },
      ]},
      { type: "verse", label: "Verse 2", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 14 }], lyric: "Somewhere over the rainbow" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 14 }], lyric: "Bluebirds fly" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "F", pos: 14 }], lyric: "And the dreams that you dream of" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "Am", pos: 10 }, { chord: "F", pos: 20 }], lyric: "Dreams really do come true" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "C", pos: 0 }], lyric: "Someday I'll wish upon a star" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "Am", pos: 16 }, { chord: "F", pos: 24 }], lyric: "Wake up where the clouds are far behind me" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "Where trouble melts like lemon drops" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "High above the chimney tops" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 14 }], lyric: "That's where you'll find me" },
      ]},
      { type: "verse", label: "Verse 3", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 14 }], lyric: "Somewhere over the rainbow" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 14 }], lyric: "Bluebirds fly" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "F", pos: 14 }], lyric: "And the dreams that you dare to" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "Am", pos: 10 }, { chord: "F", pos: 20 }], lyric: "Oh why, oh why can't I?" },
      ]},
      { type: "bridge", label: "Bridge", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 14 }], lyric: "Well I see trees of green and red roses too" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 14 }], lyric: "I'll watch them bloom for me and you" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 14 }], lyric: "And I think to myself" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 14 }], lyric: "What a wonderful world" },
      ]},
      { type: "bridge", label: "Bridge 2", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 14 }], lyric: "Well I see skies of blue and I see clouds of white" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 14 }], lyric: "And the brightness of day" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 14 }], lyric: "I like the dark and I think to myself" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 14 }], lyric: "What a wonderful world" },
      ]},
      { type: "verse", label: "Verse 4", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 14 }], lyric: "Somewhere over the rainbow" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 14 }], lyric: "Way up high" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "F", pos: 14 }], lyric: "And the dreams that you dare to" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "Am", pos: 10 }, { chord: "F", pos: 20 }], lyric: "Oh why, oh why can't I?" },
      ]},
      { type: "outro", label: "Outro", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 14 }], lyric: "Ooh... ooh..." },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 14 }], lyric: "Ooh..." },
        { chords: [{ chord: "C", pos: 0 }], lyric: "Ooh..." },
      ]},
    ]
  },
  {
    id: "allstar",
    title: "All Star",
    artist: "Smash Mouth",
    capo: 0,
    difficulty: 2,
    patternId: 4,
    bpm: 104,
    sections: [
      { type: "info", label: "Info", lines: [
        { chords: [], lyric: "No capo. G D Am C throughout — all open chords. Upbeat pop-rock, keep the strum driving and consistent. Great singalong energy." },
      ]},
      { type: "verse", label: "Verse 1", lines: [
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Somebody once told me the world is gonna roll me" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "C", pos: 20 }], lyric: "I ain't the sharpest tool in the shed" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "She was looking kind of dumb with her finger and her thumb" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "C", pos: 20 }], lyric: "In the shape of an L on her forehead" },
      ]},
      { type: "verse", label: "Verse 1 (cont.)", lines: [
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Well the years start coming and they don't stop coming" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "C", pos: 20 }], lyric: "Fed to the rules and I hit the ground running" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Didn't make sense not to live for fun" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "C", pos: 20 }], lyric: "Your brain gets smart but your head gets dumb" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "So much to do, so much to see" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "C", pos: 20 }], lyric: "So what's wrong with taking the back streets?" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "You'll never know if you don't go" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "C", pos: 20 }], lyric: "You'll never shine if you don't glow" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 12 }, { chord: "G", pos: 20 }], lyric: "Hey now, you're an all star" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 12 }, { chord: "G", pos: 20 }], lyric: "Get your game on, go play" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 12 }, { chord: "G", pos: 20 }], lyric: "Hey now, you're a rock star" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 12 }, { chord: "G", pos: 20 }], lyric: "Get the show on, get paid" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "C", pos: 14 }, { chord: "D", pos: 24 }], lyric: "And all that glitters is gold" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "C", pos: 14 }, { chord: "D", pos: 24 }], lyric: "Only shooting stars break the mould" },
      ]},
      { type: "verse", label: "Verse 2", lines: [
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "It's a cool place and they say it gets colder" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "C", pos: 20 }], lyric: "You're bundled up now, wait till you get older" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "But the media men beg to differ" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "C", pos: 20 }], lyric: "Judging by the hole in the satellite picture" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "The ice we skate is getting pretty thin" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "C", pos: 20 }], lyric: "The water's getting warm so you might as well swim" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "My world's on fire, how about yours?" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "C", pos: 20 }], lyric: "That's the way I like it and I'll never get bored" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 12 }, { chord: "G", pos: 20 }], lyric: "Hey now, you're an all star" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 12 }, { chord: "G", pos: 20 }], lyric: "Get your game on, go play" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 12 }, { chord: "G", pos: 20 }], lyric: "Hey now, you're a rock star" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 12 }, { chord: "G", pos: 20 }], lyric: "Get the show on, get paid" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "C", pos: 14 }, { chord: "D", pos: 24 }], lyric: "And all that glitters is gold" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "C", pos: 14 }, { chord: "D", pos: 24 }], lyric: "Only shooting stars break the mould" },
      ]},
      { type: "verse", label: "Verse 3", lines: [
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Somebody once asked could I spare some change for gas" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "C", pos: 20 }], lyric: "I need to get myself away from this place" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "I said yep, what a concept" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "C", pos: 20 }], lyric: "I could use a little fuel myself" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "And we could all use a little change" },
      ]},
      { type: "chorus", label: "Chorus (Final)", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 12 }, { chord: "G", pos: 20 }], lyric: "Hey now, you're an all star" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 12 }, { chord: "G", pos: 20 }], lyric: "Get your game on, go play" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 12 }, { chord: "G", pos: 20 }], lyric: "Hey now, you're a rock star" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 12 }, { chord: "G", pos: 20 }], lyric: "Get the show on, get paid" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "C", pos: 14 }, { chord: "D", pos: 24 }], lyric: "And all that glitters is gold" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "C", pos: 14 }, { chord: "D", pos: 24 }], lyric: "Only shooting stars break the mould" },
      ]},
    ]
  },
  {
    id: "someonelikeyou",
    title: "Someone Like You",
    artist: "Adele",
    capo: 2,
    difficulty: 1,
    patternId: 5,
    bpm: 68,
    sections: [
      { type: "info", label: "Info", lines: [
        { chords: [], lyric: "Capo 2. Originally in A major — capo gives you nice open G shapes. Slow ballad, let the chords ring out. Fingerpicking the verses sounds beautiful, strum the chorus." },
      ]},
      { type: "verse", label: "Verse 1", lines: [
        { chords: [{ chord: "G", pos: 0 }], lyric: "I heard that you're settled down" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "That you found a girl" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "and you're married now" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "I heard that your dreams came true" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "Guess she gave you things" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "I didn't give to you" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "" },
      ]},
      { type: "verse", label: "Verse 2", lines: [
        { chords: [{ chord: "G", pos: 0 }], lyric: "Old friend, why are you so shy?" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "Ain't like you to hold back" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "or hide from the light" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "" },
      ]},
      { type: "chorus", label: "Pre-Chorus", lines: [
        { chords: [{ chord: "D", pos: 0 }], lyric: "I hate to turn up out of the blue uninvited" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "But I couldn't stay away, I couldn't fight it" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "I had hoped you'd see my face" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 14 }], lyric: "and that you'd be reminded that for me" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "it isn't over" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 14 }], lyric: "Never mind, I'll find someone like you" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 14 }], lyric: "I wish nothing but the best for you too" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 14 }], lyric: "Don't forget me, I beg" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 14 }], lyric: "I remember you said" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 14 }], lyric: "Sometimes it lasts in love" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 14 }], lyric: "but sometimes it hurts instead" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 14 }], lyric: "Sometimes it lasts in love" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 14 }], lyric: "but sometimes it hurts instead" },
      ]},
      { type: "verse", label: "Verse 3", lines: [
        { chords: [{ chord: "G", pos: 0 }], lyric: "You know how the time flies" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "Only yesterday" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "was the time of our lives" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "We were born and raised" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "in a summer haze" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "Bound by the surprise" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "of our glory days" },
      ]},
      { type: "chorus", label: "Pre-Chorus 2", lines: [
        { chords: [{ chord: "D", pos: 0 }], lyric: "I hate to turn up out of the blue uninvited" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "But I couldn't stay away, I couldn't fight it" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "I had hoped you'd see my face" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 14 }], lyric: "and that you'd be reminded that for me" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "it isn't over" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 14 }], lyric: "Never mind, I'll find someone like you" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 14 }], lyric: "I wish nothing but the best for you too" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 14 }], lyric: "Don't forget me, I beg" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 14 }], lyric: "I remember you said" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 14 }], lyric: "Sometimes it lasts in love" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 14 }], lyric: "but sometimes it hurts instead" },
      ]},
      { type: "bridge", label: "Bridge", lines: [
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 14 }], lyric: "Nothing compares, no worries or cares" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 14 }], lyric: "Regrets and mistakes, they're memories made" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 14 }], lyric: "Who would have known how bittersweet" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "this would taste?" },
      ]},
      { type: "chorus", label: "Chorus (Final)", lines: [
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 14 }], lyric: "Never mind, I'll find someone like you" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 14 }], lyric: "I wish nothing but the best for you" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 14 }], lyric: "Don't forget me, I beg" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 14 }], lyric: "I remember you said" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 14 }], lyric: "Sometimes it lasts in love" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 14 }], lyric: "but sometimes it hurts instead" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 14 }], lyric: "Sometimes it lasts in love" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 14 }], lyric: "but sometimes it hurts instead" },
      ]},
    ]
  },
  {
    id: "stickseason",
    title: "Stick Season",
    artist: "Noah Kahan",
    capo: 2,
    difficulty: 2,
    patternId: 2,
    bpm: 130,
    sections: [
      { type: "info", label: "Info", lines: [
        { chords: [], lyric: "Capo 2. Four chords throughout: Em G D C. Folk-rock energy — keep the strum driving. Great for building confidence with fast chord changes." },
      ]},
      { type: "verse", label: "Verse 1", lines: [
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 20 }], lyric: "As you promised me that I was more than all the miles combined" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "C", pos: 20 }], lyric: "You must have had yourself a change of heart like halfway through the drive" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 20 }], lyric: "'Cause your voice trailed off exactly as you passed my exit sign" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "C", pos: 20 }], lyric: "You kept on drivin' straight and left our future to the right" },
      ]},
      { type: "verse", label: "Verse 2", lines: [
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 20 }], lyric: "Now I am stuck between my anger and the blame that I can't face" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "C", pos: 20 }], lyric: "And memories are somethin' even smokin' weed does not replace" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 20 }], lyric: "And I am terrified of weather 'cause I see you when it rains" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "C", pos: 20 }], lyric: "Doc told me to travel, but there's Covid on the planes" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 20 }], lyric: "And I love Vermont, but it's the season of the sticks" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "C", pos: 20 }], lyric: "And I saw your mom, she forgot that I existed" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 20 }], lyric: "And it's half my fault, but I just like to play the victim" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "C", pos: 20 }], lyric: "I'll drink alcohol 'til my friends come home for Christmas" },
      ]},
      { type: "chorus", label: "Chorus (cont.)", lines: [
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 20 }], lyric: "And I'll dream each night of some version of you" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "C", pos: 20 }], lyric: "That I might not have, but I did not lose" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 20 }], lyric: "Now you're tire tracks and one pair of shoes" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "C", pos: 20 }], lyric: "And I'm split in half, but that'll have to do" },
      ]},
      { type: "verse", label: "Verse 3", lines: [
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 20 }], lyric: "So I thought that if I piled somethin' good on all my bad" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "C", pos: 20 }], lyric: "That I could cancel out the darkness I inherited from dad" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 20 }], lyric: "No, I am no longer funny, 'cause I miss the way you laugh" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "C", pos: 20 }], lyric: "You once called me forever, now you still can't call me back" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 20 }], lyric: "And I love Vermont, but it's the season of the sticks" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "C", pos: 20 }], lyric: "And I saw your mom, she forgot that I existed" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 20 }], lyric: "And it's half my fault, but I just like to play the victim" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "C", pos: 20 }], lyric: "I'll drink alcohol 'til my friends come home for Christmas" },
      ]},
      { type: "chorus", label: "Chorus (cont.)", lines: [
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 20 }], lyric: "And I'll dream each night of some version of you" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "C", pos: 20 }], lyric: "That I might not have, but I did not lose" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 20 }], lyric: "Now you're tire tracks and one pair of shoes" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "C", pos: 20 }], lyric: "And I'm split in half, but that'll have to do" },
      ]},
      { type: "bridge", label: "Bridge", lines: [
        { chords: [{ chord: "Em", pos: 0 }], lyric: "Oh, that'll have to do" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "My other half was you" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "I hope this pain's just passin' through" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "But I doubt it" },
      ]},
      { type: "chorus", label: "Chorus (Final)", lines: [
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 20 }], lyric: "And I love Vermont, but it's the season of the sticks" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "C", pos: 20 }], lyric: "And I saw your mom, she forgot that I existed" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 20 }], lyric: "And it's half my fault, but I just like to play the victim" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "C", pos: 20 }], lyric: "I'll drink alcohol 'til my friends come home for Christmas" },
      ]},
      { type: "chorus", label: "Chorus (Final cont.)", lines: [
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 20 }], lyric: "And I'll dream each night of some version of you" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "C", pos: 20 }], lyric: "That I might not have, but I did not lose" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 20 }], lyric: "Now you're tire tracks and one pair of shoes" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "C", pos: 20 }], lyric: "And I'm split in half, but that'll have to do" },
      ]},
    ]
  },
  {
    id: "beautifulthings",
    title: "Beautiful Things",
    artist: "Benson Boone",
    capo: 1,
    difficulty: 2,
    patternId: 4,
    bpm: 108,
    sections: [
      { type: "info", label: "Info", lines: [
        { chords: [], lyric: "Capo 1. D A Bm G throughout. The Bm is a barre chord — practice transitioning from D to Bm. Builds from soft verses to a powerful chorus." },
      ]},
      { type: "verse", label: "Verse 1", lines: [
        { chords: [{ chord: "D", pos: 0 }], lyric: "I found my mind, I'm feeling sane" },
        { chords: [{ chord: "A", pos: 0 }], lyric: "It's been a while, but I'm finding my faith" },
        { chords: [{ chord: "Bm", pos: 0 }], lyric: "If everything's a gift" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "Then give me more time to accept it" },
      ]},
      { type: "verse", label: "Verse 2", lines: [
        { chords: [{ chord: "D", pos: 0 }], lyric: "I found my girl, we got a place" },
        { chords: [{ chord: "A", pos: 0 }], lyric: "And now I think I might be okay" },
        { chords: [{ chord: "Bm", pos: 0 }], lyric: "For the first time in my life" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "I'm not waiting on the day to come" },
      ]},
      { type: "chorus", label: "Pre-Chorus", lines: [
        { chords: [{ chord: "D", pos: 0 }, { chord: "A", pos: 16 }], lyric: "I know things change and I know things go" },
        { chords: [{ chord: "Bm", pos: 0 }, { chord: "G", pos: 16 }], lyric: "But I don't want to let this one go" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "D", pos: 0 }], lyric: "Please don't take" },
        { chords: [{ chord: "A", pos: 0 }], lyric: "my beautiful things" },
        { chords: [{ chord: "Bm", pos: 0 }], lyric: "I know I ask for too much" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "but please don't take them" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "Please don't take" },
        { chords: [{ chord: "A", pos: 0 }], lyric: "my beautiful things" },
        { chords: [{ chord: "Bm", pos: 0 }], lyric: "I know I ask for too much" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "of every person I love" },
      ]},
      { type: "verse", label: "Verse 3", lines: [
        { chords: [{ chord: "D", pos: 0 }], lyric: "I found my boy, he keeps me warm" },
        { chords: [{ chord: "A", pos: 0 }], lyric: "He heard my voice when I was calling on the Lord" },
        { chords: [{ chord: "Bm", pos: 0 }], lyric: "For something more" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "I don't deserve to ask for" },
      ]},
      { type: "chorus", label: "Pre-Chorus 2", lines: [
        { chords: [{ chord: "D", pos: 0 }, { chord: "A", pos: 16 }], lyric: "I know things change and I know things go" },
        { chords: [{ chord: "Bm", pos: 0 }, { chord: "G", pos: 16 }], lyric: "But I don't want to let this one go" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "D", pos: 0 }], lyric: "Please don't take" },
        { chords: [{ chord: "A", pos: 0 }], lyric: "my beautiful things" },
        { chords: [{ chord: "Bm", pos: 0 }], lyric: "I know I ask for too much" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "but please don't take them" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "Please don't take" },
        { chords: [{ chord: "A", pos: 0 }], lyric: "my beautiful things" },
        { chords: [{ chord: "Bm", pos: 0 }], lyric: "I know I ask for too much" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "of every person I love" },
      ]},
      { type: "bridge", label: "Bridge", lines: [
        { chords: [{ chord: "Bm", pos: 0 }, { chord: "G", pos: 16 }], lyric: "Don't take, don't take away from me" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "A", pos: 16 }], lyric: "Don't take, don't take away from me" },
        { chords: [{ chord: "Bm", pos: 0 }, { chord: "G", pos: 16 }], lyric: "Don't take, don't take away from me" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "A", pos: 16 }], lyric: "Don't take, don't take my beautiful things" },
      ]},
      { type: "chorus", label: "Chorus (Final)", lines: [
        { chords: [{ chord: "D", pos: 0 }], lyric: "Please don't take" },
        { chords: [{ chord: "A", pos: 0 }], lyric: "my beautiful things" },
        { chords: [{ chord: "Bm", pos: 0 }], lyric: "I know I ask for too much" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "but please don't take them" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "Please don't take" },
        { chords: [{ chord: "A", pos: 0 }], lyric: "my beautiful things" },
        { chords: [{ chord: "Bm", pos: 0 }], lyric: "I know I ask for too much" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "of every person I love" },
      ]},
    ]
  },
];
