export const SAMPLE_SONGS = [
  {
    id: "wonderwall",
    title: "Wonderwall",
    artist: "Oasis",
    capo: 2,
    difficulty: 2,
    patternId: 4,
    bpm: 87,
    sections: [
      { type: "verse", label: "Verse 1", lines: [
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 24 }], lyric: "Today is gonna be the day that they're" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "gonna throw it back to you" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 24 }], lyric: "By now you should've somehow realised" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "what you gotta do" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 24 }], lyric: "I don't believe that anybody" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "feels the way I do about you now" },
      ]},
      { type: "verse", label: "Verse 2", lines: [
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 24 }], lyric: "Backbeat, the word is on the street that the" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "fire in your heart is out" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 24 }], lyric: "I'm sure you've heard it all before but you" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "never really had a doubt" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 24 }], lyric: "I don't believe that anybody" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "feels the way I do about you now" },
      ]},
      { type: "chorus", label: "Pre-Chorus", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 18 }], lyric: "And all the roads we have to walk are winding" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 18 }], lyric: "And all the lights that lead us there are blinding" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "There are many things that I would" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "G", pos: 18 }], lyric: "like to say to you but I don't know how" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 10 }, { chord: "G", pos: 18 }], lyric: "Because maybe..." },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "you're gonna be the one that saves me" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 10 }, { chord: "G", pos: 18 }], lyric: "And after all..." },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "you're my wonderwall" },
      ]},
      { type: "verse", label: "Verse 3", lines: [
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 24 }], lyric: "Today was gonna be the day but they'll" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "never throw it back to you" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 24 }], lyric: "By now you should've somehow realised" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "what you're not to do" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "G", pos: 24 }], lyric: "I don't believe that anybody" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "feels the way I do about you now" },
      ]},
      { type: "chorus", label: "Pre-Chorus 2", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 18 }], lyric: "And all the roads that lead you there were winding" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 18 }], lyric: "And all the lights that light the way are blinding" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "There are many things that I would" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "G", pos: 18 }], lyric: "like to say to you but I don't know how" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 10 }, { chord: "G", pos: 18 }], lyric: "I said maybe..." },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "you're gonna be the one that saves me" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 10 }, { chord: "G", pos: 18 }], lyric: "And after all..." },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "you're my wonderwall" },
      ]},
      { type: "outro", label: "Outro", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 10 }, { chord: "G", pos: 18 }], lyric: "I said maybe..." },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "you're gonna be the one that saves me" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 10 }, { chord: "G", pos: 18 }], lyric: "you're gonna be the one that saves me" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "you're gonna be the one that saves me" },
      ]},
    ]
  },
  {
    id: "hallelujah",
    title: "Hallelujah",
    artist: "Leonard Cohen",
    capo: 0,
    difficulty: 2,
    patternId: 5,
    bpm: 56,
    sections: [
      { type: "verse", label: "Verse 1", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "Am", pos: 24 }], lyric: "I've heard there was a secret chord" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Am", pos: 24 }], lyric: "That David played and it pleased the Lord" },
        { chords: [{ chord: "F", pos: 0 }, { chord: "G", pos: 18 }], lyric: "But you don't really care for music" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 18 }], lyric: "do ya?" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "F", pos: 10 }, { chord: "G", pos: 18 }], lyric: "It goes like this, the fourth, the fifth" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 18 }], lyric: "The minor fall, the major lift" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "E", pos: 10 }, { chord: "Am", pos: 18 }], lyric: "The baffled king composing" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "F", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 10 }, { chord: "C", pos: 20 }], lyric: "Hallelu-u-u-jah" },
      ]},
      { type: "verse", label: "Verse 2", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "Am", pos: 24 }], lyric: "Your faith was strong but you needed proof" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Am", pos: 24 }], lyric: "You saw her bathing on the roof" },
        { chords: [{ chord: "F", pos: 0 }, { chord: "G", pos: 18 }], lyric: "Her beauty and the moonlight" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 18 }], lyric: "overthrew ya" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "F", pos: 10 }, { chord: "G", pos: 18 }], lyric: "She tied you to a kitchen chair" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 18 }], lyric: "She broke your throne, she cut your hair" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "E", pos: 10 }, { chord: "Am", pos: 18 }], lyric: "And from your lips she drew the" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "F", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 10 }, { chord: "C", pos: 20 }], lyric: "Hallelu-u-u-jah" },
      ]},
      { type: "verse", label: "Verse 3", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "Am", pos: 24 }], lyric: "Baby I've been here before" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Am", pos: 24 }], lyric: "I know this room, I've walked this floor" },
        { chords: [{ chord: "F", pos: 0 }, { chord: "G", pos: 18 }], lyric: "I used to live alone" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 18 }], lyric: "before I knew ya" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "F", pos: 10 }, { chord: "G", pos: 18 }], lyric: "I've seen your flag on the marble arch" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 18 }], lyric: "Love is not a victory march" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "E", pos: 10 }, { chord: "Am", pos: 18 }], lyric: "It's a cold and it's a broken" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "F", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 10 }, { chord: "C", pos: 20 }], lyric: "Hallelu-u-u-jah" },
      ]},
      { type: "verse", label: "Verse 4", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "Am", pos: 24 }], lyric: "There was a time you let me know" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Am", pos: 24 }], lyric: "What's real and going on below" },
        { chords: [{ chord: "F", pos: 0 }, { chord: "G", pos: 18 }], lyric: "But now you never show" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 18 }], lyric: "it to me, do ya?" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "F", pos: 10 }, { chord: "G", pos: 18 }], lyric: "Remember when I moved in you" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 18 }], lyric: "The holy dove was moving too" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "E", pos: 10 }, { chord: "Am", pos: 18 }], lyric: "And every breath we drew was" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "F", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 10 }, { chord: "C", pos: 20 }], lyric: "Hallelu-u-u-jah" },
      ]},
      { type: "verse", label: "Verse 5", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "Am", pos: 24 }], lyric: "I did my best, it wasn't much" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Am", pos: 24 }], lyric: "I couldn't feel, so I tried to touch" },
        { chords: [{ chord: "F", pos: 0 }, { chord: "G", pos: 18 }], lyric: "I've told the truth, I didn't come" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 18 }], lyric: "to fool ya" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "F", pos: 10 }, { chord: "G", pos: 18 }], lyric: "And even though it all went wrong" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 18 }], lyric: "I'll stand before the Lord of Song" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "E", pos: 10 }, { chord: "Am", pos: 18 }], lyric: "With nothing on my tongue but" },
      ]},
      { type: "chorus", label: "Chorus (Final)", lines: [
        { chords: [{ chord: "F", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 10 }, { chord: "C", pos: 20 }], lyric: "Hallelu-u-u-jah" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "Hallelujah" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 10 }, { chord: "C", pos: 20 }], lyric: "Hallelu-u-u-jah" },
      ]},
    ]
  },
  {
    id: "fastcar",
    title: "Fast Car",
    artist: "Tracy Chapman",
    capo: 2,
    difficulty: 2,
    patternId: 2,
    bpm: 105,
    sections: [
      { type: "info", label: "Info", lines: [
        { chords: [], lyric: "Capo 2. Four chords throughout: C G Em D. Verses are fingerpicked (work up to that), chorus is strummed. Great for building right-hand independence." },
      ]},
      { type: "verse", label: "Verse 1", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "You got a fast car, and" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "I want a ticket to anywhere" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "Maybe we make a deal" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Maybe together we can get somewhere" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "Any place is better" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Starting from zero got nothing to lose" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "Maybe we'll make something, but" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "me myself I got nothing to prove" },
      ]},
      { type: "verse", label: "Verse 2", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "You got a fast car, but" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "is it fast enough so we can fly away?" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "We gotta make a decision" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Leave tonight or live and die this way" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "C", pos: 0 }], lyric: "So I remember when we were driving," },
        { chords: [{ chord: "G", pos: 0 }], lyric: "driving in your car" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "The speed so fast I felt like I was drunk" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "City lights lay out before us" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 16 }, { chord: "D", pos: 24 }], lyric: "and I had a feeling that I belonged" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 16 }, { chord: "D", pos: 24 }], lyric: "and I had a feeling I could be someone" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 16 }], lyric: "be someone, be someone" },
      ]},
      { type: "verse", label: "Verse 3", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "You got a fast car, and" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "I got a plan to get us out of here" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "I been working at the convenience store" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Managed to save just a little bit of money" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "Won't have to drive too far" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Just 'cross the border and into the city" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "You and I can both get jobs and" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "finally see what it means to be living" },
      ]},
      { type: "verse", label: "Verse 4", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "You got a fast car, and" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "we go cruising to entertain ourselves" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "You still ain't got a job and" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "I work in a market as a checkout girl" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "I know things will get better" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "You'll find work and I'll get promoted" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "We'll move out of the shelter" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Buy a big house and live in the suburbs" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "C", pos: 0 }], lyric: "So I remember when we were driving," },
        { chords: [{ chord: "G", pos: 0 }], lyric: "driving in your car" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "The speed so fast I felt like I was drunk" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "City lights lay out before us" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 16 }, { chord: "D", pos: 24 }], lyric: "and I had a feeling that I belonged" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 16 }, { chord: "D", pos: 24 }], lyric: "and I had a feeling I could be someone" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 16 }], lyric: "be someone, be someone" },
      ]},
      { type: "verse", label: "Verse 5", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "You got a fast car, and" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "I got a job that pays all our bills" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "You stay out drinking late at the bar" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "See more of your friends than you do of your kids" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "I'd always hoped for better" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Thought maybe together you and me would find it" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "I got no plans, I ain't going nowhere" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "So take your fast car and keep on driving" },
      ]},
      { type: "chorus", label: "Chorus (Final)", lines: [
        { chords: [{ chord: "C", pos: 0 }], lyric: "So I remember when we were driving," },
        { chords: [{ chord: "G", pos: 0 }], lyric: "driving in your car" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "The speed so fast I felt like I was drunk" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "City lights lay out before us" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 16 }, { chord: "D", pos: 24 }], lyric: "and I had a feeling that I belonged" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "Em", pos: 16 }, { chord: "D", pos: 24 }], lyric: "and I had a feeling I could be someone" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "D", pos: 16 }], lyric: "be someone, be someone" },
      ]},
      { type: "verse", label: "Outro", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "You got a fast car, but" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "is it fast enough so you can fly away?" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "You gotta make a decision" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Leave tonight or live and die this way" },
      ]},
    ]
  },
  {
    id: "someoneyouloved",
    title: "Someone You Loved",
    artist: "Lewis Capaldi",
    capo: 1,
    difficulty: 1,
    patternId: 2,
    bpm: 110,
    sections: [
      { type: "info", label: "Info", lines: [
        { chords: [], lyric: "Capo 1. Same four chords the whole song: C G Am F. One of the easiest songs to strum along to — focus on getting the rhythm solid." },
      ]},
      { type: "verse", label: "Verse 1", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 24 }], lyric: "I'm going under and this time" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 24 }], lyric: "I fear there's no one to save me" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 24 }], lyric: "This all or nothing really got a way" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 24 }], lyric: "of driving me crazy" },
      ]},
      { type: "verse", label: "Pre-Chorus", lines: [
        { chords: [{ chord: "C", pos: 0 }], lyric: "I need somebody to heal" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "Somebody to know" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "Somebody to have" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "Somebody to hold" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "It's easy to say" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "But it's never the same" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "I guess I kinda liked the way" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "you numbed all the pain" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "C", pos: 0 }], lyric: "Now the day bleeds" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "Into nightfall" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "And you're not here" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "To get me through it all" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "I let my guard down" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "And then you pulled the rug" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "I was getting kinda used to" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "being someone you loved" },
      ]},
      { type: "verse", label: "Verse 2", lines: [
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 24 }], lyric: "I'm going under and this time" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 24 }], lyric: "I fear there's no one to turn to" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 24 }], lyric: "This all or nothing way of loving" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 24 }], lyric: "got me sleeping without you" },
      ]},
      { type: "verse", label: "Pre-Chorus", lines: [
        { chords: [{ chord: "C", pos: 0 }], lyric: "Now I need somebody to know" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "Somebody to heal" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "Somebody to have" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "Just to know how it feels" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "It's easy to say" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "But it's never the same" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "I guess I kinda liked the way" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "you numbed all the pain" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "C", pos: 0 }], lyric: "Now the day bleeds" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "Into nightfall" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "And you're not here" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "To get me through it all" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "I let my guard down" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "And then you pulled the rug" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "I was getting kinda used to" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "being someone you loved" },
      ]},
      { type: "bridge", label: "Bridge", lines: [
        { chords: [{ chord: "C", pos: 0 }], lyric: "I let my guard down" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "I let my guard down" },
        { chords: [{ chord: "Am", pos: 0 }, { chord: "F", pos: 20 }], lyric: "I was getting kinda used to being someone you loved" },
      ]},
      { type: "chorus", label: "Chorus (Final)", lines: [
        { chords: [{ chord: "C", pos: 0 }], lyric: "Now the day bleeds" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "Into nightfall" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "And you're not here" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "To get me through it all" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "I let my guard down" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "And then you pulled the rug" },
        { chords: [{ chord: "Am", pos: 0 }], lyric: "I was getting kinda used to" },
        { chords: [{ chord: "F", pos: 0 }], lyric: "being someone you loved" },
      ]},
    ]
  },
  {
    id: "allofme",
    title: "All of Me",
    artist: "John Legend",
    capo: 0,
    difficulty: 2,
    patternId: 5,
    bpm: 63,
    sections: [
      { type: "info", label: "Info", lines: [
        { chords: [], lyric: "No capo needed. Em C G D throughout. Slow tempo — good for practising smooth chord changes. The Am in the bridge is a nice easy addition." },
      ]},
      { type: "verse", label: "Verse 1", lines: [
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 20 }], lyric: "What would I do without your smart mouth" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Drawing me in, and you kicking me out" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 20 }], lyric: "Got my head spinning, no kidding" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "I can't pin you down" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 20 }], lyric: "What's going on in that beautiful mind" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "I'm on your magical mystery ride" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 20 }], lyric: "And I'm so dizzy, don't know what hit me" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "But I'll be alright" },
      ]},
      { type: "verse", label: "Pre-Chorus", lines: [
        { chords: [{ chord: "Am", pos: 0 }], lyric: "My head's under water" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "But I'm breathing fine" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "You're crazy and I'm out of my mind" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "G", pos: 0 }], lyric: "'Cause all of me" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "loves all of you" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "Love your curves and all your edges" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "All your perfect imperfections" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "Give your all to me" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "I'll give my all to you" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "You're my end and my beginning" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "Even when I lose I'm winning" },
      ]},
      { type: "verse", label: "Verse 2", lines: [
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 20 }], lyric: "How many times do I have to tell you" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Even when you're crying you're beautiful too" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 20 }], lyric: "The world is beating you down" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "I'm around through every mood" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 20 }], lyric: "You're my downfall, you're my muse" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "My worst distraction, my rhythm and blues" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 20 }], lyric: "I can't stop singing, it's ringing" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "in my head for you" },
      ]},
      { type: "verse", label: "Pre-Chorus", lines: [
        { chords: [{ chord: "Am", pos: 0 }], lyric: "My head's under water" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "But I'm breathing fine" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "You're crazy and I'm out of my mind" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "G", pos: 0 }], lyric: "'Cause all of me" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "loves all of you" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "Love your curves and all your edges" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "All your perfect imperfections" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "Give your all to me" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "I'll give my all to you" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "You're my end and my beginning" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "Even when I lose I'm winning" },
      ]},
      { type: "bridge", label: "Bridge", lines: [
        { chords: [{ chord: "Am", pos: 0 }], lyric: "Give me all of you" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "Cards on the table, we're both showing hearts" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "Risking it all, though it's hard" },
      ]},
      { type: "chorus", label: "Chorus (Final)", lines: [
        { chords: [{ chord: "G", pos: 0 }], lyric: "'Cause all of me" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "loves all of you" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "Love your curves and all your edges" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "All your perfect imperfections" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "Give your all to me" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "I'll give my all to you" },
        { chords: [{ chord: "C", pos: 0 }], lyric: "You're my end and my beginning" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "Even when I lose I'm winning" },
        { chords: [{ chord: "G", pos: 0 }], lyric: "'Cause I give you all of me" },
        { chords: [{ chord: "Em", pos: 0 }], lyric: "And you give me all of you" },
      ]},
    ]
  },
  {
    id: "countryroads",
    title: "Take Me Home, Country Roads",
    artist: "John Denver",
    capo: 2,
    difficulty: 1,
    patternId: 4,
    bpm: 82,
    sections: [
      { type: "info", label: "Info", lines: [
        { chords: [], lyric: "Capo 2. Mostly open chords you already know. The F in the bridge is a barre — good practice! You can substitute Fmaj7 (xx3210) if F is still tricky." },
      ]},
      { type: "verse", label: "Verse 1", lines: [
        { chords: [{ chord: "G", pos: 0 }, { chord: "Em", pos: 24 }], lyric: "Almost heaven, West Virginia" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "C", pos: 14 }, { chord: "G", pos: 24 }], lyric: "Blue Ridge Mountains, Shenandoah River" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "Em", pos: 24 }], lyric: "Life is old there, older than the trees" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "C", pos: 14 }, { chord: "G", pos: 24 }], lyric: "Younger than the mountains, growing like a breeze" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Country roads, take me home" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 20 }], lyric: "To the place I belong" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "West Virginia, mountain mama" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "Take me home, country roads" },
      ]},
      { type: "verse", label: "Verse 2", lines: [
        { chords: [{ chord: "G", pos: 0 }, { chord: "Em", pos: 24 }], lyric: "All my memories gather round her" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "C", pos: 14 }, { chord: "G", pos: 24 }], lyric: "Miner's lady, stranger to blue water" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "Em", pos: 24 }], lyric: "Dark and dusty, painted on the sky" },
        { chords: [{ chord: "D", pos: 0 }, { chord: "C", pos: 14 }, { chord: "G", pos: 24 }], lyric: "Misty taste of moonshine, teardrop in my eye" },
      ]},
      { type: "bridge", label: "Bridge", lines: [
        { chords: [{ chord: "Em", pos: 0 }, { chord: "D", pos: 16 }], lyric: "I hear her voice in the mornin' hour she calls me" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "C", pos: 12 }, { chord: "G", pos: 24 }], lyric: "The radio reminds me of my home far away" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "F", pos: 24 }], lyric: "And drivin' down the road I get a feelin' that I" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 14 }], lyric: "should have been home yesterday" },
        { chords: [{ chord: "D", pos: 0 }], lyric: "yesterday" },
      ]},
      { type: "chorus", label: "Chorus", lines: [
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Country roads, take me home" },
        { chords: [{ chord: "Em", pos: 0 }, { chord: "C", pos: 20 }], lyric: "To the place I belong" },
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "West Virginia, mountain mama" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "Take me home, country roads" },
      ]},
      { type: "outro", label: "Outro", lines: [
        { chords: [{ chord: "G", pos: 0 }, { chord: "D", pos: 20 }], lyric: "Take me home, down country roads" },
        { chords: [{ chord: "C", pos: 0 }, { chord: "G", pos: 20 }], lyric: "Take me home, down country roads" },
      ]},
    ]
  },
];
